name: Python Mocking POC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
     build:

       runs-on: ubuntu-latest

       steps:
       - uses: actions/checkout@v2
       - name: Set up Python 3.8
         uses: actions/setup-python@v2
         with:
           python-version: 3.8
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install flake8
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
       - name: Lint with flake8
         run: |
           # stop the build if there are Python syntax errors or undefined names
           flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
           # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
           flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
       - name: Test with unittest
         run: |
           python main_tests.py

     - name: Install Coverage.py
        run: pip3 install -U coverage

      - name: Validate Coverage.py Version
        run: python3 -c 'import coverage; print(coverage.__version__)'
